"""add_profile_visibility_to_user

Revision ID: 3af626eb8f34
Revises: 57c6866dcca5
Create Date: 2026-08-13 15:26:21.243686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af626eb8f34'
down_revision: Union[str, Sequence[str], None] = '57c6866dcca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_visibility', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_visibility')
    # ### end Alembic commands ###
