"""Add ScheduledCall new fields

Revision ID: 57c6866dcca5
Revises: 32d2db425644
Create Date: 2026-08-13 13:57:14.493902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c6866dcca5'
down_revision: Union[str, Sequence[str], None] = '32d2db425644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_calls', sa.Column('description', sa.String(), nullable=True))
    op.add_column('scheduled_calls', sa.Column('call_type', sa.String(), nullable=True))
    op.add_column('scheduled_calls', sa.Column('chat_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'scheduled_calls', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduled_calls', type_='foreignkey')
    op.drop_column('scheduled_calls', 'chat_id')
    op.drop_column('scheduled_calls', 'call_type')
    op.drop_column('scheduled_calls', 'description')
    # ### end Alembic commands ###
