"""Add is_edited and is_deleted to Message

Revision ID: 8579d4af0124
Revises: 4d71d1876b81
Create Date: 2026-08-13 11:29:15.002120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8579d4af0124'
down_revision: Union[str, Sequence[str], None] = '4d71d1876b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_edited', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_deleted')
    op.drop_column('messages', 'is_edited')
    # ### end Alembic commands ###
