"""add_description_and_permissions_to_chats

Revision ID: 91bf02618a78
Revises: f9ad323459c0
Create Date: 2026-08-14 00:16:57.596677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91bf02618a78'
down_revision: Union[str, Sequence[str], None] = 'f9ad323459c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('description', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('only_admins_can_post', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('chats', sa.Column('only_admins_can_edit_info', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('chats', sa.Column('only_admins_can_add_members', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('chats', sa.Column('allow_prayer_requests', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('chats', sa.Column('allow_calls', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('chats', sa.Column('pinned_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'pinned_message')
    op.drop_column('chats', 'allow_calls')
    op.drop_column('chats', 'allow_prayer_requests')
    op.drop_column('chats', 'only_admins_can_add_members')
    op.drop_column('chats', 'only_admins_can_edit_info')
    op.drop_column('chats', 'only_admins_can_post')
    op.drop_column('chats', 'description')
    # ### end Alembic commands ###
