"""add_group_image_to_chat

Revision ID: f9ad323459c0
Revises: 3af626eb8f34
Create Date: 2026-08-13 15:33:01.949083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ad323459c0'
down_revision: Union[str, Sequence[str], None] = '3af626eb8f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('group_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'group_image')
    # ### end Alembic commands ###
